title: Xiangjie Zhao
url: "https://cadenzhao.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/CadenZhao"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
# - name: "Resume"
#   link: "resume.pdf"
 - name: "Skills"
   link: "skills"
 - name: "Projects"
   link: "projects"
 - name: "Talks"
   link: "talks"
 - name: "Publications"
   link: "publications"
 - name: "Contact"
   link: "contact"
